global using System.Collections.Immutable;
global using System.Windows.Input;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Controls.Primitives;
global using Microsoft.UI.Xaml.Automation.Peers;
global using Microsoft.UI.Xaml.Automation;
global using Microsoft.UI.Xaml.Input;
global using Microsoft.UI.Xaml.Markup;
global using MUXC = Microsoft.UI.Xaml.Controls;
